name: release_base

on:
   workflow_dispatch:
      inputs:
         version:
            description: "The release version"
            required: true
         branch:
            description: "The branch to release from"
            required: true
            default: 'master'

env:
   RELEASE_VERSION: ${{ inputs.version }}
   ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
   ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
   NEW_MAVEN_CENTRAL_USERNAME: ${{ secrets.NEW_MAVEN_CENTRAL_USERNAME }}
   NEW_MAVEN_CENTRAL_PASSWORD: ${{ secrets.NEW_MAVEN_CENTRAL_PASSWORD }}

permissions:
   contents: read

jobs:
   publish_base:
      if: github.repository == 'kotest/kotest'
      runs-on: ubuntu-latest
            if: github.repository == 'kotest/kotest'
      strategy:
            if: github.repository == 'kotest/kotest'
         max-parallel: 1
                  if: github.repository == 'kotest/kotest'
         matrix:
                  if: github.repository == 'kotest/kotest'
            target:
                        if: github.repository == 'kotest/kotest'
               - publishKotlinMultiplatformPublicationToDeployRepository
               - publishJvmPublicationToDeployRepository
               - publishJsPublicationToDeployRepository
               - publishWasmJsPublicationToDeployRepository
               - publishKotestBomPublicationToDeployRepository
               - publishLinuxX64PublicationToDeployRepository
               - publishLinuxArm64PublicationToDeployRepository
               - publishAndroidNativeX86PublicationToDeployRepository
               - publishAndroidNativeX64PublicationToDeployRepository
               - publishAndroidNativeArm32PublicationToDeployRepository
               - publishAndroidNativeArm64PublicationToDeployRepository
      steps:
            if: github.repository == 'kotest/kotest'
         -  name: Checkout the repo
            uses: actions/checkout@v4
                        if: github.repository == 'kotest/kotest'
            with:
                        if: github.repository == 'kotest/kotest'
               ref: ${{ inputs.branch }}
                              if: github.repository == 'kotest/kotest'

         -  name: Setup JDK
            uses: actions/setup-java@v4
                        if: github.repository == 'kotest/kotest'
            with:
                        if: github.repository == 'kotest/kotest'
               distribution: "temurin"
                              if: github.repository == 'kotest/kotest'
               java-version-file: .github/.java-version
                              if: github.repository == 'kotest/kotest'

         -  uses: gradle/actions/setup-gradle@v4

         -  name: publish
            run: ./gradlew ${{ matrix.target }}
                        if: github.repository == 'kotest/kotest'
