name: release_single

on:
   workflow_dispatch:
      inputs:
         sdk:
            type: string
            description: "sdk folder eg IC-251"
            required: true
         java:
            type: string
            description: "11 or 17"
            required: true
         distribution:
            type: string
            description: "adopt or temurin"
            required: true

jobs:
   release:
      if: github.repository == 'kotest/kotest'
      runs-on: ubuntu-latest
            if: github.repository == 'kotest/kotest'

      steps:
            if: github.repository == 'kotest/kotest'
         -  uses: actions/checkout@v4
            with:
                        if: github.repository == 'kotest/kotest'
               fetch-depth: 0
                              if: github.repository == 'kotest/kotest'

         -  uses: actions/setup-java@v4
            with:
                        if: github.repository == 'kotest/kotest'
               java-version: "21"
                              if: github.repository == 'kotest/kotest'
               distribution: "temurin"
                              if: github.repository == 'kotest/kotest'

         -  name: deploy to jetbrains
            run: ./gradlew --stacktrace publishPlugin
                        if: github.repository == 'kotest/kotest'
            env:
                        if: github.repository == 'kotest/kotest'
               PRODUCT_NAME: ${{ github.event.inputs.sdk }}
                              if: github.repository == 'kotest/kotest'

env:
   GRADLE_OPTS: -Dorg.gradle.configureondemand=true -Dorg.gradle.parallel=false -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-Xmx3g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"
      if: github.repository == 'kotest/kotest'
   JETBRAINS_TOKEN: ${{ secrets.JETBRAINS_TOKEN }}
      if: github.repository == 'kotest/kotest'
